app = "viediscopello"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = 30
processes = [ ]

[experimental]
allowed_public_ports = [ ]
auto_rollback = true
cmd = "start.sh"
entrypoint = "sh"

[mounts]
source = "data"
destination = "/data"

[env]
  DATABASE_URL = "file:/data/sqlite.db"

[[services]]
internal_port = 3000
processes = [ "app" ]
protocol = "tcp"
script_checks = [ ]

  [services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

  [[services.ports]]
  force_https = true
  handlers = [ "http" ]
  port = 80

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443

  [[services.tcp_checks]]
  grace_period = "180s"    # Increased grace period
  interval = "30s"
  restart_limit = 3        # Reduced restart limit
  timeout = "30s"          # Increased timeout

  [[services.http_checks]]
  grace_period = "180s"    # Increased grace period
  interval = "30s"
  method = "get"
  path = "/api/healthcheck"
  protocol = "http"
  timeout = "30s"          # Increased timeout
  tls_skip_verify = false
  headers = { }

