app = "viediscopello"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = 30

[env]
  PORT = "3000"
  DATABASE_URL = "file:/data/sqlite.db"

[[vm]]
  cpu_kind = "shared"
  memory_mb = 1024
  min_machines_running = 1

[mounts]
  source = "data"
  destination = "/data"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "30s"
    grace_period = "180s"
    method = "get"
    path = "/api/healthcheck"
    protocol = "http"
    timeout = "30s"

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "30s"
    restart_limit = 3
    grace_period = "180s"

  [[services.http_checks]]
    interval = "30s"
    grace_period = "180s"
    method = "get"
    path = "/api/healthcheck"
    protocol = "http"
    timeout = "30s"
    tls_skip_verify = false
    headers = { }

